CREATE TABLE user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(25) NOT NULL,
  name VARCHAR(250) NOT NULL
);

CREATE TABLE employee (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  salary INT NOT NULL,
  age INT NOT NULL
);
